plugins {
    id 'java'
    id 'application'
}

group = 'dev.yahya'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

repositories {
    mavenCentral()
}

application {
    mainClass = 'dev.yahya.player.MusicPlayerApp'
}
